#docker compose file for teal
version: '2'
services:

 redis:
  container_name: redis
  image: redis

 live_manager: 
  container_name: live-manager
  build: ./live-manager

 mongo:
  container_name: mongo
  image: mongo
  volumes: 
   # match the default location for mongodb in the host
   - /data/db:/data/db

 teal:
  container_name: teal
  environment:
   - RACK_ENV=production
  build: .
  depends_on:
   - mongo
   - redis
  volumes:
   - /data/teal-media:/data/teal-media
  command: bundle exec puma

 recorder:
  container_name: recorder
  environment:
   - RACK_ENV=production
  build: ./recorder
  depends_on:
   - teal
  command: ruby recorder.rb

 encode_worker:
  build: .
  container_name: encode_worker
  volumes:
   - /data/teal-media:/data/teal-media
  depends_on:
   - redis
   - mongo
  environment:
   - RACK_ENV=production
  command: "bundle exec rake resque:work QUEUE=encode"

 nginx:
  container_name: nginx
  build:
   context: .
   dockerfile: Dockerfile-nginx
  volumes: 
   - /var/lib/acme/:/var/lib/acme/:ro
  ports:
   - "80:80"
   - "443:443"
  depends_on:
   - teal
