#docker compose file for teal
redis:
 container_name: redis
 image: redis

mongo:
 container_name: mongo
 image: mongo
 volumes: 
  # match the default location for mongodb in the host
  - /data/db:/data/db

teal:
 container_name: teal
 environment:
  - RACK_ENV=production
 build: .
 links:
  - mongo
  - redis
 volumes:
  - /data/teal_media:/data/teal_media
 command: bundle exec puma -p 9000 -w 4 --preload

worker:
 build: .
 command: bundle exec rake environment resque:work QUEUE=*
 volumes:
  - /data/teal_media:/data/teal_media
 links:
  - redis
 environment:
  - REDIS_URL=redis
 
nginx:
 container_name: nginx
 image: nginx
 #get the nginx config file from the config folder
 volumes: 
  - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
 ports:
  - "80:80"
  - "443:443"
 links:
  - teal
