#docker compose file for teal
version: '2'
services:
 redis:
  container_name: redis
  image: redis

 mongo:
  container_name: mongo
  image: mongo
  volumes: 
   # match the default location for mongodb in the host
   - /data/db:/data/db

 teal:
  container_name: teal
  environment:
   - RACK_ENV=production
  build: .
  links:
   - mongo
   - redis
  volumes:
   - /data/teal-media:/data/teal-media
  command: bundle exec puma -p 9000 -w 4 --preload

 encode_worker:
  build: .
  container_name: encode_worker
  volumes:
   - /data/teal-media:/data/teal-media
  links:
   - redis
   - mongo
  environment:
   - RACK_ENV=production
  command: "bundle exec rake resque:work QUEUE=encode"
 
 nginx:
  container_name: nginx
  image: nginx
  #get the nginx config file from the config folder
  volumes: 
   - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
   - ./frontend:/frontend:ro
  ports:
   - "80:80"
   - "443:443"
  links:
   - teal
