development:
  clients:
    default:
      database: tealmongoid
      hosts:
        - localhost:27017

production:
  clients:
    default:
      database: tealmongoid
      hosts:
        - mongo:27017


