# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61736a611c2ff3fbf7c771be168b5b4e3a9ce5c7ddfab1952fae40e5a131f164841206615bd4f7627d996f63c51c438a1ab9e7e4d9f0278fee52a1f9ee8d02e1

test:
  secret_key_base: 53b5dcb65c027e84dfa92d3985fa6d9fecfb5a66840705ccaf1e02bcabcde3417f8169cd3ef7f89aea4e3ed353cbb4484e898527027f783a46126ababc70a4d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
